# Generated by Django 2.2.4 on 2019-08-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuartel', '0002_auto_20190822_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compania',
            name='id_compania',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
